### PR TITLE
Fix for wrong resolution on multi-monitor Windows 10 system

### LINKED ISSUE #26: Wrong resolution on Windows when scaled
I have two monitors on a Windows 10 laptop. The inbuilt display is set to 125% scale in Settings - see pic. But screeninfo gives the wrong resolution - it scales it by 125% and returns 1536x864 instead of 1920x1080. Can I have it return an unscaled resolution please?

image

### PR DESCRIPTION
**Pull request by benshep**
Fixes #26

### CODE REVIEW

**Comment by hhannine** [comment]
As per the "Setting default awareness programmatically" table here https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v=vs.85)
SetProcessDpiAwareness is supported from Win8.1 onwards. A decision needs to be made whether Win7/Vista support is desired. Given that Win7 is EOL I propose that screeninfo need not support Win7 functionality, and as such the current patch does fix the issue on the supported platforms (Win8.1+).

**Comment by benshep** [comment]
Presumably you could check the Windows version if the previous code works on Win7?

**Comment by hhannine** [comment]
In principle yes but if we don't have a test system we'd be supporting it blindfolded anyway. And given that official support has ended the user base is going to be tiny and dwindling. Not worth the extra complexity in my view.

**Comment by hhannine** [comment]
@rr- What do you think?

**Comment by rr-** [comment]
I'll review it this afternoon

**Comment by rr-** [comment]
Merged manually

**Comment by rr-** [comment]
Released as 0.6.3. Thanks.

**Pull request closed without merging**
