### PR TITLE
Added get_primary to screeninfo and exposed it from __init__.py

### PR DESCRIPTION
**Pull request by TyrotoxismB**
This would be an useful function for the **primary** usage of this package: to get the width and height of the primary monitor.

### CODE REVIEW

**Comment by TyrotoxismB** [comment]
Pretty sure those tests will pass in workflow :)

**Comment by TyrotoxismB** [comment]
This last commit can be dismissed as it's purely visual. It depends on the maintainers desires really.

**Comment by TyrotoxismB** [comment]
This commit was so I don't wake up tonight in a cold sweat.

**Comment by TyrotoxismB** [comment]
I just realized this can be cached in memory to avoid that issue... That would be a better solution.

**Comment by TyrotoxismB** [comment]
> I just realized this can be cached in memory to avoid that issue... That would be a better solution.

Nevermind, I think this current implementation is better because it also covers new monitors, I presume.

**Comment by TyrotoxismB** [comment]
I slightly tweaked the README format to better accommodate the addition of a new function, I also corrected `python console` to `pycon`.

**Comment by rr-** [comment]
Thanks. This utility function seems so specific that I don't think it makes sense to ship it with the library.

```
primary = list(map(lambda m: (m.width, m.height), filter(lambda m: m.is_primary, get_monitors())))
```

**Pull request closed without merging**
