### PR TITLE
Workaround for bad device contexts on Windows which cause enumeration to fail randomly

### PR DESCRIPTION
**Pull request by hhannine**

### CODE REVIEW

**Comment by hhannine** [comment]
Should fix #25 .

Couldn't figure out how to arrange commits more cleanly.

**Comment by hhannine** [comment]
Can you not do the squashing on your end like you did last time? I can't quite figure out how I should handle squashing the old batch of commits that already were merged into master and the new merge from master and patch?

**Comment by rr-** [comment]
All right but please address my other remarks

**Comment by hhannine** [comment]
As to why this was solved this way, to condense the discussion from #25 
- GetDC seems to fail randomly producing a DC with negative ID which is invalid.
- This negative DC then causes the Enumeration fail completely producing no output.
- I could not find a cause for this regression causing the bad DCs
- Probability of failure was low enough and the fetches are fast enough to just try a number of times to get a good DC
- Fallback uses DC of 0 which is the whole desktop which will produce resolutions but no display sizes which need display specific DCs in the callback.
- I added the ReleaseDCs as you suggested for safety but they didn't seem to affect functionality.

**Comment by hhannine** [comment]
Do you want me to replace the while loop with a for-break-else construct? I hadn't seen that one before so it would be a bit of effort to rewrite and test to be sure I get it right.

**Comment by rr-** [comment]
The comment should go into code, not here. 

>Do you want me to replace the while loop with a for-break-else construct?

Yes, please, it'll improve readability a lot.

**Comment by hhannine** [comment]
I rewrote the loop and added some terse comments, hopefully they will do.

**Comment by rr-** [comment]
Merged manually. Thanks

**Pull request closed without merging**
