### PR TITLE
`is_primary` boolean for Monitor objects

### PR DESCRIPTION
**Pull request by cedric-romain**
Okay that went smoother as expected. I hope this fits. Thanks for any feedback. #52

### CODE REVIEW

**Review by rr- — COMMENTED** [review]
Let's add typing annotations

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
Let's also make sure the formatting is OK

**Comment by cedric-romain** [comment]
oh thanks, I did overlook that.

**Comment by rr-** [comment]
One last thing – I think we also need to update the documentation in the README.

```
from screeninfo import get_monitors
for m in get_monitors():
    print(str(m))
```

README currently says that the code above will output:

```
>Monitor(x=1920, y=0, width=1920, height=1080, name=None)  
>Monitor(x=0, y=0, width=1920, height=1080, name=None)
```

but I think it will also now show `, is_primary=False` and `, is_primary=True` in addition.

**Comment by cedric-romain** [comment]
Good catch. Should i also add the part `width_mm=None, height_mm=None` or should that be done in a separate commit?

**Comment by rr-** [comment]
Let's update it all at once, and I'll try to think of a way to make sure GitHub actions catch future documentation slip-ups

**Comment by cedric-romain** [comment]
Fantastic. Thanks for your support. This was a first for me. I will follow the updates here 😊

**Comment by rr-** [comment]
Thank you for the pull request and responding quickly 👍

**Comment by cedric-romain** [comment]
Right back at you.
Also: will you update the version or should I have done that? Not sure about the procedure.
And: not sure why (maybe it was a coincidence the last time?) but the Output in the README has the new line in the middle of the output.

**Comment by rr-** [comment]
@cedric-romain I've updated the README and added tests so that it won't be neglected again, should we add more properties to the `Monitor` class. I'll release a new version now.

**Comment by rr-** [comment]
Released as 0.7.

**Comment by cedric-romain** [comment]
Awesome. Thanks again. That was very insightful.

**Pull request merged**
