### PR TITLE
chore: ports project to poetry

### PR DESCRIPTION
**Pull request by betafcc**
I took longer than planed earlier today trying to contribute with just a couple of lines: https://github.com/rr-/screeninfo/pull/59

Mostly because didn't have a requirements.txt or some lockfile. Also my `.venv` folder and `__pycache__` where being tracked 

This PR ports the project to [PEP517](https://www.python.org/dev/peps/pep-0517/) compliant structure using [poetry](https://python-poetry.org/) as a build tool (since [setuptools is no longer default](https://setuptools.pypa.io/en/latest/userguide/index.html#transition-to-pep517) and poetry is the closest to a consensus for modern packaging)

### CODE REVIEW

**Comment by rr-** [comment]
Thanks. Before we can merge this we'll need to adjust GitHub actions. Also I'd prefer to not pollute .gitignore with IDE-specific settings. Is poetry capable of shipping packages to pypi?

**Comment by betafcc** [comment]
@rr- 
> Thanks. Before we can merge this we'll need to adjust GitHub actions. 
Ah you are right, I forgot to check the config properly

> Also I'd prefer to not pollute .gitignore with IDE-specific settings.

the .gitignore was just the standard one: https://github.com/github/gitignore/blob/master/Python.gitignore
Indeed has obscure use cases in mind, but usually is included as standard

> Is poetry capable of shipping packages to pypi?
Yes, just `poetry publish` : https://python-poetry.org/docs/libraries/#publishing-to-pypi

Currently the biggest solutions for modern python workflow are [pipenv](https://pipenv.pypa.io/en/latest/) and [poetry](https://python-poetry.org/), pipenv is actually way more popular, since the creator is well know in the community (is the same from the well know requests package), but for some reason doesn't not comply with PEP517 and does not handle packaging (is aimed at 'applications' instead of 'libs'), so poetry is the one to go

In fact i came here because it's a dependency of [manim](https://github.com/ManimCommunity/manim), which happens to use poetry as well

**Comment by betafcc** [comment]
had to get a crash course on github actions config, please review https://github.com/rr-/screeninfo/pull/60/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R19-R35

I used the docs at https://github.com/snok/install-poetry#testing

**Comment by betafcc** [comment]
sorry for the failed workflow, improper indenting on config file 😅

**Review by rr- — COMMENTED** [review]
One more thing. Does this require users of this package to use poetry? Is pip compatible with pyproject.toml?

**Comment by betafcc** [comment]
@rr- it's not needed to use poetry to work on the project, pip is pyproject.toml compatible, meaning, if you do:

```sh
git clone https://github.com/rr-/screeninfo
cd screeninfo
pip install .
```
Everything will work as before, installing only runtime dependencies.

It will not install the dev-dependencies thought, in that case you need to do manually as was the case before anyway.

By PEP517, pip will read 'build-system' and note 'poetry-core' as build dependency (instead of the setuptools that was before) and will bootstrap with the info this backend provides, which takes everything from the pyproject.toml itself, instead of the setup.py and setup.cfg files that setuptools uses.

In short, poetry just orchestrates venv + pip + setuptools + pyenv under a unified interface

If you plan to keep non-poetry workflow support, I suggest at least including a freeze from the local environment so others can replicate it, you do it by `pip freeze > requirements.txt`.

Also, if you are not using already, it's important to work on the project only under a venv:

```sh
python -m venv .venv
source .venv/bin/activate
```

This guarantees that your global installed libraries does not appear on the project, so you don't get confused of which dependencies are installed on the project and which are on your computer

Ideally it would be important also to keep a '.pyenv' file  so everyone uses the same python version, but that may be superfluous in such a small project

Keep in mind all these recommendations are exactly the reason why poetry and pipenv are a thing nowadays, to orchestrate and automate all those fragmented tools

**Comment by rr-** [comment]
>pip is pyproject.toml compatible

Amazing! I believe that was not the case about a year ago. I am so happy to see the ecosystem finally unifying :)

**Comment by rr-** [comment]
Thank you for this pull request and for the detailed explanation of the current packaging tool situation. I really appreciate this. I learned a lot of things today :)

**Pull request merged**
