### PR TITLE
PEP518 + Test reorganisation

### PR DESCRIPTION
**Pull request by demberto**
1. PEP518 compatibility to ensure type checkers don't cry.
2. Moved tests to their own directory `tests/`.

### CODE REVIEW

**Comment by rr-** [comment]
@demberto can you rebase against newest master? Thanks.

**Comment by demberto** [comment]
Done.

**Comment by rr-** [comment]
Thanks. Do you need a new release for this?

**Comment by demberto** [comment]
> Do you need a new release for this?

sure.

**Pull request merged**
